---
    - name: "yum update"
      yum:
        name: '*'
        state: latest

    - name: "install policycoreutils-python"
      yum:
        name: policycoreutils-python

    - name: "chenge selinux policy 1"
      shell:  sudo semanage port --list | grep -q 25672 || sudo semanage port -a -t amqp_port_t -p tcp 25672; sudo setsebool -P httpd_can_network_connect 1

    - name: "add epel repo"
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

    - name: "import public key to mongo"
      shell: sudo rpm --import https://www.mongodb.org/static/pgp/server-3.2.asc

    - name: "copy repo file for mongo"
      template:
        src: mongodb-org-3.2.repo
        dest: /etc/yum.repos.d/mongodb-org-3.2.repo
        owner: root
        group: root
        mode: 0644

    - name: "install mongodb"
      yum:
        name: mongodb-org

    - name: "install rabbitmq"
      yum:
        name: rabbitmq-server

    - name: "start mongod and rabbitmq"
      shell: sudo systemctl start mongod rabbitmq-server

    - name: "enable mongod and rabbitmq"
      shell: sudo systemctl enable mongod rabbitmq-server

    - name: "install postgresql"
      yum:
        name: postgresql-server,postgresql-contrib,postgresql-devel,python-psycopg2

    - name: "initialize postgres"
      ignore_errors: yes
      shell: sudo postgresql-setup initdb

    - name: "copy pg_hba.conf"
      template:
        src: pg_hba.conf
        dest: /var/lib/pgsql/data/pg_hba.conf
        owner: postgres
        group: postgres
        mode: 0600

    - name: "copy postgresql.conf"
      template:
        src: postgresql.conf
        dest: /var/lib/pgsql/data/postgresql.conf
        owner: postgres
        group: postgres
        mode: 0600

    - name: "start postgresql"
      shell: sudo systemctl start postgresql

    - name: "enable postgresql"
      shell: sudo systemctl enable postgresql

    - name: "copy mongod.conf"
      template:
        src: mongod.conf
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: 644

    - name: "restart mongodb"
      shell: sudo systemctl restart mongod

    - name: "create role mistral to postgresql"
      postgresql_user:
        name: mistral
        role_attr_flags: CREATEDB,LOGIN
        password: StackStorm
        encrypted: true
        login_user: postgres
        login_host: 127.0.0.1

    - name: "create database mistral"
      postgresql_db:
        name: mistral
        owner: mistral
        login_user: postgres
        login_host: 127.0.0.1

    - name: "run st2 script"
      shell: curl -s https://packagecloud.io/install/repositories/StackStorm/stable/script.rpm.sh | sudo bash

    - name: "import public key to nginx"
      shell: sudo rpm --import http://nginx.org/keys/nginx_signing.key

    - name: "copy repo file for nginx"
      template:
        src: nginx.repo
        dest: /etc/yum.repos.d/
        owner: root
        group: root
        mode: 0644

    - name: "install st2web,nginx"
      yum:
        name: st2web,nginx

    - name: "make directory"
      shell: sudo mkdir -p /etc/ssl/st2

    - name: "ssl key gen"
      shell: sudo openssl req -x509 -newkey rsa:2048 -keyout /etc/ssl/st2/st2.key -out /etc/ssl/st2/st2.crt -days 365 -nodes -subj "/C=US/ST=California/L=Palo Alto/O=StackStorm/OU=Information Technology/CN=$(hostname)"

    - name: "copy st2.conf"
      template:
        src: nginx-st2controller.conf
        dest: /etc/nginx/conf.d/st2.conf
        owner: root
        group: root
        mode: 0644 

    - name: "edit nginx.conf"
      shell: sudo sed -i 's/default_server//g' /etc/nginx/nginx.conf

    - name: "restart/enable nginx"
      shell: systemctl restart nginx; systemctl enable nginx

    - name: "make directory /var/log/st2"
      shell: mkdir -p /var/log/st2

    - name: "create st2 user"
      shell: useradd st2
      register: result
      failed_when: result.rc not in [0,9]

    - name: "copy rabbitmq.config"
      template:
        src: rabbitmq.config
        dest: /etc/rabbitmq/rabbitmq.config
        owner: root
        group: root
        mode: 0644

    - name: "restart rabbitmq-server,postgresql"
      shell: systemctl restart rabbitmq-server; systemctl restart postgresql
