---
    - name: "yum update"
      yum:
        name: '*'
        state: latest

    - name: "install policycoreutils-python"
      yum:
        name: policycoreutils-python

    - name: "chenge selinux policy 1"
      shell:  sudo semanage port --list | grep -q 25672 || sudo semanage port -a -t amqp_port_t -p tcp 25672; sudo setsebool -P httpd_can_network_connect 1

    - name: "install repo for st2"
      shell: curl -s https://packagecloud.io/install/repositories/StackStorm/stable/script.rpm.sh | sudo bash

    - name: "install st2,st2mistral"
      yum:
        name: st2,st2mistral

    - name: "import public key to nginx"
      shell: sudo rpm --import http://nginx.org/keys/nginx_signing.key

    - name: "copy repo file for nginx"
      template:
        src: nginx.repo
        dest: /etc/yum.repos.d/nginx.repo
        owner: root
        group: root
        mode: 0644

    - name: "install nginx"
      yum:
        name: nginx

    - name: "copy mistral.conf"
      template:
        src: mistral.conf
        dest: /etc/mistral/mistral.conf
        owner: root
        group: root
        mode: 0644

    - name: "setup mistral database"
      shell: /opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf upgrade head
      ignore_errors: yes

    - name: "register mistral action"
      shell: /opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf populate
      ignore_errors: yes

    - name: "copy st2.conf"
      template:
       src: st2-node.conf
       dest: /etc/st2/st2.conf
       owner: root
       group: root
       mode: 0644

    - name: "make directory /etc/ssl/st2"
      shell: sudo mkdir -p /etc/ssl/st2

    - name: "generate a certificate"
      shell: sudo openssl req -x509 -newkey rsa:2048 -keyout /etc/ssl/st2/st2.key -out /etc/ssl/st2/st2.crt -days XXX -nodes -subj "/C=US/ST=California/L=Palo Alto/O=StackStorm/OU=Information Technology/CN=$(hostname)"

    - name: "install httpd-tools"
      yum:
        name: httpd-tools

    - name: "set password st2admin"
      shell: echo 'password' | sudo htpasswd -i /etc/st2/htpasswd st2admin

    - name: "restart st2"
      shell: sudo st2ctl restart-component st2api

    - name: "copy nginx config"
      template:
        src: nginx-st2node.conf
        dest: /etc/nginx/conf.d/st2.conf
        owner: root
        group: root
        mode: 0644

    - name: "restart/enable nginx"
      shell: systemctl restart nginx; systemctl enable nginx

    - name: "start st2 service"
      shell: st2ctl start

    - name: "reload st2"
      shell: st2ctl reload
